### ISSUE TITLE
Smarter backend

### ISSUE THREAD

**Issue by crertel** [sketch-city/harvey-needs#2]
Can we set this up to pull from the Google Spreadsheets directly?

That's pretty trivial using node, and I've already got the infra in place left over from the project that begat this one.

@pandafulmanda

**Comment by ironcoconut** [comment]
What about a full SQL DBA instead?

**Comment by pandafulmanda** [comment]
this was pulling from google spreadsheets directly and has since been upgraded to use https://github.com/sketch-city/harvey-api.  thanks for working that guys :)  closing this issue
