### ISSUE TITLE
Fix CSS for Panel on Map

### ISSUE THREAD

**Issue by ksmith6** [sketch-city/harvey-needs#3]
Please adjust the *Panel* CSS on the map on the landing page for harveyneeds.org.

See below:

<img width="1195" alt="screen shot 2017-08-30 at 10 16 54 pm" src="https://user-images.githubusercontent.com/1100567/29905091-20cd0730-8dd2-11e7-9acb-c33266e69731.png">

Currently, the `overflow-y` is set to `scroll`.  

I got everything to fit on the map by adjusting the `height` of the `.filterpanel input` elements to `25px` and setting the margin to `5px`.

**Comment by pandafulmanda** [comment]
thanks for this issue!  this is in reference to https://github.com/johnnyqbui/Houston-Shelters.  I'm unsure if he's made these updates and maybe these are no longer issues, but I will let him know and also close this issue.
